### PR TITLE
chore: Upgraded to Larastan 3.0 and PHPStan 2.0

### PR DESCRIPTION
**Pull request by odinns**
Upgrades dependencies and fixes code and baselines.

### CODE REVIEW

**Comment by canvural** [comment]
Hi,

Thank you for this.

And as this is a breaking change. Could you please target the 3.0.x branch?

**Comment by odinns** [comment]
> Hi,
> 
> Thank you for this.
> 
> And as this is a breaking change. Could you please target the 3.0.x branch?

Sure I can do that, but the 3.0.x branch is a lot behind in commits from the v2 branch?

**Comment by odinns** [comment]
Anyway I have done that now

**Comment by canvural** [comment]
This is really weird 🤔 

Is it possible for you to first checkout 3.0.x branch and then apply your changes? That way we'd also get rid of the merge conflicts.

**Comment by owenvoke** [comment]
Yeah, seems like it just needs to be applied onto the 3.0.x branch, can use this patch: [commit.patch](https://github.com/user-attachments/files/17976246/commit.patch) (there were some conflicts, so cleaned them up in the patch).

**Review by owenvoke — APPROVED** [review]

**Comment by odinns** [comment]
Should be good now 👍

**Comment by canvural** [comment]
One last thing: we need to adjust the Github Actions to only run the latest versions. We can copy the versions from `composer.json`

**Comment by owenvoke** [comment]
Should be able to use this patch: [commit.patch](https://github.com/user-attachments/files/17977321/commit.patch)

**Comment by odinns** [comment]
Applied the patch and pushed 👍

**Comment by canvural** [comment]
Alright, this looks good. Thank you so much @odinns and @owenvoke

**Comment by canvural** [comment]
Released: https://github.com/canvural/larastan-strict-rules/releases/tag/3.0.0

Please let me know if you encounter any issues when you try it.

**Pull request merged**
